2022-10-13 06:34:58,591 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-2de2198f3ea57d2537289c2c90d3728b
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7faa17c37880>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,603 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-03225e0bfdf6d3792a1490846be64ec8
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f33d4f9bc40>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,605 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-4008e77344741833a3b2b0e8c80ba335
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fa4a222fc40>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,605 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-de03545954f29e0d9afc079f89146104
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7faa40b5bc70>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,607 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-f4f35bcc1503629ba3ee5a96d1f1f5a6
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fb958943c40>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,608 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-f6f50b3a842e3424b2e189c57f10a2a8
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fd0ab5678b0>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,612 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-2d3b62cfa740b8fab4977b50372fccb2
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fb32878fa60>)
kwargs:    {}
Exception: 'AssertionError()'

2022-10-13 06:34:58,615 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-811628db96a616dfcbb167e79cc47c88
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fc9d060f8b0>)
kwargs:    {}
Exception: 'AssertionError()'

Distributing data time: 0.8426575660705566
Execution time: 0.18753767013549805
Traceback (most recent call last):
  File "/home/ubuntu/forms/benchmark/test_driver.py", line 50, in <module>
    result = fs.compute_formula(df, formula_str)
  File "/home/ubuntu/forms/forms/core/forms.py", line 44, in compute_formula
    res = plan_executor.df_execute_formula_plan(df, root)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/planexecutor.py", line 81, in df_execute_formula_plan
    return res_table.get_table_content()
  File "/home/ubuntu/forms/forms/executor/table.py", line 55, in get_table_content
    self.df = self.remote_df.get_df_content()
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 80, in get_df_content
    [
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 82, in <listcomp>
    [one_partition.remote_obj.get_computed_result() for one_partition in one_row],
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 82, in <listcomp>
    [one_partition.remote_obj.get_computed_result() for one_partition in one_row],
  File "/home/ubuntu/forms/forms/runtime/remoteobject.py", line 33, in get_computed_result
    return self.object_ref.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/distributed/client.py", line 277, in result
    raise exc.with_traceback(tb)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/planexecutor.py", line 45, in execute_one_subtree
    res_table = function_executor(physical_subtree)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/basicfuncexecutor.py", line 187, in sumif_df_executor
    assert op in operator_dict.keys()
AssertionError
